"""
route_key.py — Stable join keys for matching trips across runs (Eq 28).

CRITICAL FIX vs prior code (AUDIT W5): Eq 28 specifies per-(route, class)
free-flow references where "route" is an O–D identity, not a specific path.
The prior code hashed the full edge sequence, which meant vehicles taking
different paths under different congestion levels got different keys and
were dropped from WT computation.

We key on (first_non_internal_edge, last_non_internal_edge, vehicle_type).
This is stable across runs for any vehicle with fixed origin and destination,
regardless of which path SUMO actually routes them on.

For the Yan'an network specifically, trips are defined in osm.*.rou.xml with
explicit edge sequences generated by duarouter, so the first and last edges
are reliable O/D identifiers.
"""

from __future__ import annotations
from typing import Iterable, List, Tuple


def normalize_edges(edges: Iterable[str]) -> List[str]:
    """Remove SUMO internal edges (starting with ':') and drop empties."""
    out: List[str] = []
    for e in edges:
        if not e:
            continue
        if e.startswith(":"):
            continue
        out.append(e)
    return out


def make_route_key(edges: Iterable[str]) -> str:
    """
    Route key = "<first_edge>→<last_edge>".

    Per Eq 28, this identifies a route (O–D pair), not a specific path.
    Different paths between the same O and D collapse to the same key.
    """
    seq = normalize_edges(edges)
    if not seq:
        return "EMPTY"
    return f"{seq[0]}->{seq[-1]}"


def route_endpoints(edges: Iterable[str]) -> Tuple[str, str]:
    """Returns (origin_edge, destination_edge)."""
    seq = normalize_edges(edges)
    if not seq:
        return ("", "")
    return (seq[0], seq[-1])


def _tests():
    assert make_route_key(["a", "b", "c"]) == "a->c"
    assert make_route_key(["a", ":internal", "c"]) == "a->c"
    assert make_route_key([]) == "EMPTY"
    assert make_route_key(["a", "b", "c"]) == make_route_key(["a", "x", "y", "c"]), \
        "same O-D should yield same key regardless of path"
    print("route_key tests passed.")


if __name__ == "__main__":
    _tests()
